In [1]:
import csv
import os
from Target_colors import target_colors_grn, target_colors_brn
import numpy as np
from PIL import Image

Directory info

In [5]:
original_directory = os.getcwd()
os.chdir('../Pictures')
filename = '3010 C1 W-HW 9 water.JPG'

In [6]:
img = Image.open(filename)

In [7]:
size = img.size
size

(5152, 3864)

In [8]:
pix_val = img.getcolors(size[0]*size[1])
pix_val

[(58783, (255, 255, 255)),
 (5082, (254, 255, 255)),
 (286, (252, 255, 255)),
 (70, (251, 255, 255)),
 (3, (250, 255, 255)),
 (6, (249, 255, 255)),
 (2, (248, 255, 255)),
 (1, (247, 255, 255)),
 (7845, (255, 254, 255)),
 (1247, (254, 254, 255)),
 (357, (253, 254, 255)),
 (3, (252, 254, 255)),
 (20, (251, 254, 255)),
 (55, (250, 254, 255)),
 (2, (249, 254, 255)),
 (2, (247, 254, 255)),
 (2, (246, 254, 255)),
 (1, (243, 254, 255)),
 (775, (255, 253, 255)),
 (142, (254, 253, 255)),
 (622, (253, 253, 255)),
 (188, (252, 253, 255)),
 (4, (251, 253, 255)),
 (20, (250, 253, 255)),
 (29, (249, 253, 255)),
 (13, (248, 253, 255)),
 (4, (246, 253, 255)),
 (5, (245, 253, 255)),
 (1, (244, 253, 255)),
 (88, (255, 252, 255)),
 (352, (254, 252, 255)),
 (104, (253, 252, 255)),
 (7, (252, 252, 255)),
 (47, (251, 252, 255)),
 (5, (250, 252, 255)),
 (22, (249, 252, 255)),
 (30, (248, 252, 255)),
 (25, (247, 252, 255)),
 (4, (245, 252, 255)),
 (7, (244, 252, 255)),
 (3, (243, 252, 255)),
 (1, (237, 252, 2

$$\int_0^2 \sin(\pi x) dx = 0$$

In [9]:
rowname = filename.split('.')[0]
row = [rowname]

In [10]:
num_target_colors = len(target_colors_brn)

In [14]:
for i in range(num_target_colors):
    print(i)
    for set in pix_val:
        if np.array_equal(set[1][:3],target_colors_brn[i]):
            row.append(set[0])
            break
    else:
        row.append(0)
        

In [17]:
j_old = 0
for i in range(num_target_colors):
    print(i,j_old,pix_val[j_old][1])
    for j in range(j_old,len(pix_val)):
        if np.array_equal(pix_val[j][1][:3],target_colors_brn[i]):
            row.append(pix_val[j][0])
            j_old = j + 1
            break
    else:
        row.append(0)
        

0 0 (255, 255, 255)
1 583 (254, 255, 253)
2 1551 (254, 255, 248)
3 4121 (254, 255, 239)
4 4838 (254, 252, 237)
5 25691 (249, 239, 203)
6 25691 (249, 239, 203)
7 25691 (249, 239, 203)
8 25691 (249, 239, 203)
9 25691 (249, 239, 203)
10 54557 (245, 235, 174)
11 54557 (245, 235, 174)
12 54557 (245, 235, 174)
13 54557 (245, 235, 174)
14 54557 (245, 235, 174)
15 54557 (245, 235, 174)
16 54557 (245, 235, 174)
17 54557 (245, 235, 174)
18 54557 (245, 235, 174)
19 54557 (245, 235, 174)
20 54557 (245, 235, 174)
21 54557 (245, 235, 174)
22 54557 (245, 235, 174)
23 54557 (245, 235, 174)
24 54557 (245, 235, 174)
25 54557 (245, 235, 174)
26 54557 (245, 235, 174)
27 54557 (245, 235, 174)
28 54557 (245, 235, 174)
29 54557 (245, 235, 174)
30 72496 (243, 213, 159)
31 72496 (243, 213, 159)
32 72496 (243, 213, 159)
33 72496 (243, 213, 159)
34 72496 (243, 213, 159)
35 72496 (243, 213, 159)
36 72496 (243, 213, 159)
37 72496 (243, 213, 159)
38 72496 (243, 213, 159)
39 72496 (243, 213, 159)
40 72496 (243, 213,

In [15]:
rows = [row]
os.chdir(original_directory)
with open('Target_Color_Brn_counts.csv', 'a', newline='') as csv_file:
    writer = csv.writer(csv_file)
    writer.writerows(rows)

In [2]:
target_colors_brn

[array([255, 255, 253]),
 array([255, 255, 248]),
 array([255, 255, 239]),
 array([255, 252, 237]),
 array([255, 239, 203]),
 array([254, 254, 254]),
 array([254, 254, 254]),
 array([253, 253, 253]),
 array([252, 241, 211]),
 array([252, 236, 174]),
 array([251, 246, 240]),
 array([251, 234, 227]),
 array([251, 210, 192]),
 array([250, 238, 226]),
 array([250, 223, 214]),
 array([249, 236, 184]),
 array([249, 230, 190]),
 array([248, 240, 177]),
 array([248, 229, 187]),
 array([248, 212, 190]),
 array([247, 246, 244]),
 array([247, 222, 158]),
 array([247, 219, 205]),
 array([246, 244, 229]),
 array([246, 233, 227]),
 array([245, 251, 225]),
 array([245, 243, 246]),
 array([245, 239, 241]),
 array([244, 238, 224]),
 array([244, 213, 159]),
 array([243, 227, 202]),
 array([242, 231, 227]),
 array([241, 237, 226]),
 array([241, 227, 216]),
 array([240, 239, 221]),
 array([240, 225, 144]),
 array([240, 223, 215]),
 array([240, 222, 182]),
 array([238, 221, 211]),
 array([238, 218, 191]),
